//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlItla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorAsignatura
    {
        public int id { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<int> idAsignatura { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
